// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBInYpHONxNGyl8eAYb46ThkESQ2iBdO8Y',
    appId: '1:1036289006744:web:08c71cae73b1db146544ed',
    messagingSenderId: '1036289006744',
    projectId: 'diaryapp-f42e8',
    authDomain: 'diaryapp-f42e8.firebaseapp.com',
    storageBucket: 'diaryapp-f42e8.firebasestorage.app',
    measurementId: 'G-XT49EWJF50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8P2Oln6x8YatirE0Y7aTMNihi988Zeqk',
    appId: '1:1036289006744:android:6c04772c84ad33446544ed',
    messagingSenderId: '1036289006744',
    projectId: 'diaryapp-f42e8',
    storageBucket: 'diaryapp-f42e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9cXWOoObZiiMhCJNOFr9CHbB0dQHdpM',
    appId: '1:1036289006744:ios:b118be6964a705d36544ed',
    messagingSenderId: '1036289006744',
    projectId: 'diaryapp-f42e8',
    storageBucket: 'diaryapp-f42e8.firebasestorage.app',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR9cXWOoObZiiMhCJNOFr9CHbB0dQHdpM',
    appId: '1:1036289006744:ios:b118be6964a705d36544ed',
    messagingSenderId: '1036289006744',
    projectId: 'diaryapp-f42e8',
    storageBucket: 'diaryapp-f42e8.firebasestorage.app',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBInYpHONxNGyl8eAYb46ThkESQ2iBdO8Y',
    appId: '1:1036289006744:web:5374db44a3d483416544ed',
    messagingSenderId: '1036289006744',
    projectId: 'diaryapp-f42e8',
    authDomain: 'diaryapp-f42e8.firebaseapp.com',
    storageBucket: 'diaryapp-f42e8.firebasestorage.app',
    measurementId: 'G-05XEC34CC9',
  );

}